group: admin
name: cluster-settings
description: KetaDB 集群配置
path: admin/internal/_cluster/settings
methods:
  list:
    description: KetaDB 集群配置 - list
    http:
      method: GET
      query:
        format: json
  exclude_by_name:
    description: KetaDB 集群配置 - exclude_by_name
    http:
      method: PUT
    params:
      body:
      - name: name
        type: string
        description: 节点名称，从集群中排除指定名称的节点
  exclude_by_ip:
    description: KetaDB 集群配置 - exclude_by_ip
    http:
      method: PUT
    params:
      body:
      - name: ip
        type: string
        description: 节点IP地址，从集群中排除指定IP的节点
  restore_exclude:
    description: KetaDB 集群配置 - restore_exclude
    http:
      method: PUT
  set:
    description: KetaDB 集群配置 - set
    http:
      method: PUT
    params:
      body:
      - name: key
        type: string
        description: 配置项名称，如 thread_pool.write.queue_size
      - name: value
        type: string
        description: 配置项值，如 10
