[project]
name = "ketaops-cli"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["cliyard>=0.1.0", "antlr4-python3-runtime"]

[project.scripts]
ketaops-cli = "ketaops_cli.main:main"

[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"ketaops_cli" = ["specs/*.yaml", "specs/plugins/*.py"]
