"""``cliyard gen`` — Generate a standalone CLI tool from YAML specs.

Usage::

    cliyard gen --name ketacliv2 --defs-path tests/fixtures/spec-dir/
    cd dist/ketacliv2 && pip install -e .
    ketacliv2 repos list --help
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import yaml  # noqa: F401 — used in gen() for parsing resource YAMLs

import click

_PYPROJECT_TOML_TEMPLATE = """\
[project]
name = "{CLI_NAME}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["cliyard>=0.1.0"]

[project.scripts]
{CLI_NAME} = "{pkg_name}.main:main"

[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"{pkg_name}" = ["specs/*.yaml", "specs/plugins/*.py"]
"""

_MAIN_PY_TEMPLATE = """\
\"\"\"CLI entry point. Edit this file to customize commands.\"\"\"
import sys
from pathlib import Path
from click.exceptions import UsageError
from cliyard.runtime import create_cli

_SPEC_DIR = Path(__file__).parent / "specs"


def main():
    try:
        cli = create_cli(str(_SPEC_DIR))
        sys.exit(cli(standalone_mode=False))
    except UsageError as e:
        sys.exit(e.format_message())
"""
_INIT_PY = ""

_README_TEMPLATE = """\
# {CLI_NAME}

Generated by [cliyard](https://github.com/example/cliyard).

## Install

```bash
pip install -e .
```

## Usage

```bash
# Show available commands
{CLI_NAME} --help

# Authenticate (first time)
{CLI_NAME} auth add -n myenv -e <endpoint> -u <user> -p <pass>

# Or use an existing token
{CLI_NAME} auth add -n myenv -e <endpoint> -t <token>

# Run commands
{CLI_NAME} <resource> list --page-size 10
{CLI_NAME} <resource> list --format json
```

## Adding new resources

1. Create a YAML file in `src/{pkg_name}/specs/` (copy an existing one as reference):

```yaml
description: My resource
path: myresource
methods:
  list:
    http:
      method: GET
    output:
      items_path: $.items
      fields:
        - name: id
          alias: ID
  create:
    http:
      method: POST
    params:
      body:
        - name: name
          type: string
          required: true
```

2. Re-run `cliyard gen --name {CLI_NAME}` in the project directory to regenerate the CLI.

## Customizing commands

Edit `src/{pkg_name}/main.py` to add custom logic, interceptors, or new commands:

```python
# Add a new command directly
@cli.command()
def my_custom_command():
    \"\"\"Custom logic.\"\"\"
    print("Hello from {CLI_NAME}!")
```

## Adding plugins

Create a `.py` file in `src/{pkg_name}/specs/plugins/`:

```python
from cliyard.plugin import register_auth_step, register_hook

@register_auth_step("custom_login")
class CustomLogin:
    def execute(self, auth_state, config, http_client):
        # Custom auth logic
        token = "my-token"
        http_client.default_headers["Authorization"] = f"Bearer {token}"
        auth_state["token"] = token
        return token

@register_hook("custom_hook")
def custom_hook(req):
    req.headers["X-Custom"] = "value"
    return req
```

Reference plugins in `_auth.yaml`:

```yaml
auth:
  steps:
    - name: login
      type: plugin:custom_login
```

## Custom method plugins

For business logic that involves multiple API calls, write a method plugin:

```python
# src/{pkg_name}/specs/plugins/my_biz.py
from cliyard.plugin import register_method

@register_method("multi_step_import")
def multi_step_import(params, http_client, config):
    # Step 1: prepare
    r1 = http_client.request("POST", "/api/prepare", data=params)
    # Step 2: transform and commit
    r2 = http_client.request("POST", "/api/commit", json=r1.json())
    return {"status": "done", "id": r2.json().get("id")}
```

Reference it in a resource YAML:

```yaml
methods:
  import:
    type: plugin:multi_step_import
    config:
      batch_size: 100
    params:
      body:
        - name: source
          type: string
          required: true
```

The plugin function receives ``params`` (validated CLI args), ``http_client``
(authenticated), and ``config`` (from YAML). The return value is JSON output.

## Multiple environments

```bash
# Add environments
{CLI_NAME} auth add -n dev -e https://dev.example.com -t <token>
{CLI_NAME} auth add -n prod -e https://prod.example.com -t <token> --default

# Switch between them
{CLI_NAME} auth switch prod
{CLI_NAME} --env prod <resource> list
```
"""


@click.command()
@click.option("--name", required=True, help="Name of the generated CLI tool")
@click.option(
    "--defs-path",
    default=None,
    type=click.Path(exists=True, file_okay=False, resolve_path=True),
    help="Path to YAML spec directory (omit for empty scaffold)",
)
@click.option(
    "--output",
    default=None,
    type=click.Path(file_okay=False, resolve_path=True),
    help="Output directory (default: ./<name>/)",
)
def gen(name: str, defs_path: str | None, output: str | None) -> None:
    """Generate a standalone CLI tool from YAML specs.

    Reads a cliyard service spec directory (containing ``_auth.yaml``
    and resource YAML files) and produces a pip-installable Python package
    in the output directory. If ``--defs-path`` is omitted, generates an
    empty scaffold that you can fill in later.
    """
    pkg_name = name.replace("-", "_")
    output_dir = Path(output) if output else Path.cwd() / name
    output_dir = output_dir.resolve()

    # Create output structure
    src_dir = output_dir / "src" / pkg_name
    specs_dir = src_dir / "specs"
    specs_dir.mkdir(parents=True, exist_ok=True)

    click.echo(f"✔ Created output directory: {output_dir}")

    # 1. Validate or create defs-path
    if defs_path:
        spec_dir = Path(defs_path).resolve()
        service_yaml = spec_dir / "_auth.yaml"
        if not service_yaml.exists():
            click.echo(f"Error: {spec_dir} does not contain _auth.yaml", err=True)
            sys.exit(1)
        click.echo(f"✔ Found _auth.yaml in {spec_dir}")
    else:
        # No --defs-path: check if output specs/ already has YAMLs
        existing_svc = specs_dir / "_auth.yaml"
        if existing_svc.exists():
            spec_dir = specs_dir  # Regenerate from existing specs
            click.echo(f"✔ Reusing specs from {specs_dir}")
        else:
            spec_dir = None
            # Generate a minimal _auth.yaml for the scaffold
            scaffold_svc = specs_dir / "_auth.yaml"
            scaffold_svc.write_text(f"""\
name: {name}
version: "0.1.0"
description: CLI for {name}
server:
  base_url: http://localhost:8080
""")
            click.echo("✔ Generated empty scaffold (add YAMLs to src/{pkg_name}/specs/)")

    # 2. Generate pyproject.toml

    # 3. Generate pyproject.toml
    pyproject_path = output_dir / "pyproject.toml"
    pyproject_path.write_text(
        _PYPROJECT_TOML_TEMPLATE
        .replace("{CLI_NAME}", name)
        .replace("{pkg_name}", pkg_name)
    )
    click.echo(f"✔ Generated pyproject.toml")

    # 4. Generate src/<pkg_name>/__init__.py
    init_path = src_dir / "__init__.py"
    init_path.write_text(_INIT_PY)
    click.echo(f"✔ Generated src/{pkg_name}/__init__.py")

    # 5. Generate src/<pkg_name>/main.py (thin wrapper around create_cli)
    main_path = src_dir / "main.py"
    main_path.write_text(_MAIN_PY_TEMPLATE)
    click.echo(f"✔ Generated src/{pkg_name}/main.py")

    # 6. Copy spec files (skip if already in specs_dir)
    copied = 0
    if spec_dir and spec_dir.resolve() != specs_dir.resolve():
        for yaml_file in sorted(spec_dir.glob("*.yaml")):
            dest = specs_dir / yaml_file.name
            shutil.copy2(yaml_file, dest)
            copied += 1
    elif spec_dir and spec_dir.resolve() == specs_dir.resolve():
        copied = len(list(spec_dir.glob("*.yaml")))  # Already in place
    click.echo(f"✔ Copied {copied} spec file(s) to src/{pkg_name}/specs/")

    # 6b. Copy plugins directory if it exists
    if spec_dir:
        plugins_src = spec_dir / "plugins"
        if plugins_src.is_dir():
            plugins_dest = specs_dir / "plugins"
            shutil.copytree(plugins_src, plugins_dest, dirs_exist_ok=True)
            click.echo(f"✔ Copied plugins/ to src/{pkg_name}/specs/plugins/")

    # 7. Generate README.md
    readme_path = output_dir / "README.md"
    readme_path.write_text(
        _README_TEMPLATE
        .replace("{CLI_NAME}", name)
        .replace("{pkg_name}", pkg_name)
    )
    click.echo(f"✔ Generated README.md")

    click.echo()
    click.echo(f"Package generated at {output_dir}")
    click.echo(f"To install:  cd {output_dir} && pip install -e .")
    click.echo(f"To use:      {name} --help")
